services:
  najeewoods_dashboard:
    build: ./vide-connect-dashboard
    image: arifbiswas/najeewoods_dashboard:latest
    container_name: najeewoods_dashboard
    ports:
      - 5050:5050
    env_file:
      - ./vide-connect-dashboard/.env
      # - ./najeewoods_dashboard/.env
    environment:
      PORT: 5050
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network
