name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: production
    env:
     IMAGE_NAME: arifbiswas/najeewoods_dashboard
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # (Steps for Node setup, install, test, and build app remain the same)

      - name: Build Docker Image
        # Tag the image with the repository name and version/commit SHA
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/najeewoods_dashboard:latest .
      
      # --- NEW STEPS FOR DOCKER REGISTRY DEPLOYMENT ---
      
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  
      - name: Build & Push
        env:
         IMAGE_NAME: arifbiswas/najeewoods_dashboard
        run: |
          docker buildx build \
          --platform linux/amd64 \
          -t $IMAGE_NAME:latest \
          --push .



      # --- REVISED DEPLOYMENT STEP ---

      - name: SSH Into Server & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/ 
            ls
            docker compose up -d
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}